services:
  - type: web
    name: product-backend
    env: docker
    repo: https://github.com/alphayogi22/product-catalogue-app
    branch: main
    region: oregon
    rootDir: backend_mongo
    plan: free

  - type: web
    name: product-frontend
    repo: https://github.com/alphayogi22/product-catalogue-app
    branch: main
    region: oregon
    rootDir: product-app
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    plan: free
