services:
  - type: web
    name: product-backend
    env: docker
    plan: free
    repo: https://github.com/alphayogi22/product-catalogue-app
    branch: main
    rootDir: backend_mongo
    region: oregon
    envVars:
      - key: ConnectionStrings__MongoDb
        value: mongodb+srv://yogeshratudi97:8XWtncpbVmLf3yvi@productcluster.vapxfpp.mongodb.net/?retryWrites=true&w=majority&appName=ProductCluster

  - type: static
    name: product-frontend
    plan: free
    repo: https://github.com/alphayogi22/product-catalogue-app
    branch: main
    rootDir: product-app
    buildCommand: npm install && npm run build
    staticPublishPath: build
    region: oregon
