name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend_mongo/**'
      - '.github/workflows/backend.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend_mongo/backend_mongo.csproj

      - name: Build
        run: dotnet build ./backend_mongo/backend_mongo.csproj --configuration Release

      - name: Publish
        run: dotnet publish ./backend_mongo/backend_mongo.csproj --configuration Release --output ./backend_mongo/out

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: ./backend_mongo/out
