name: Backend CI/CD Render Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend_mongo/**"
      - ".github/workflows/backend.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (validate locally)
        run: |
          docker build -t product-backend ./backend_mongo

      - name: Trigger deploy on Render
        run: |
            curl -X POST "https://api.render.com/v1/services/${{ srv-d1ir21h5pdvs73avq9u0 }}/deploys" \
          -H "Authorization: Bearer ${{ rnd_hO07p9xu5WZNk0MQqh3RwQk89xpL }}" \
          -H "Accept: application/json" \
          -d '{}'

