name: Frontend CI/CD Netlify Deploy

on:
  push:
    branches:
      - main
    paths:
      - "product-app/**"
      - ".github/workflows/frontend.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd product-app
          npm install

      - name: Build React app
        run: |
          cd product-app
          npm run build

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          cd product-app
          netlify deploy --dir=build --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
