name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'product-app/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: product-app
        run: npm install

      - name: Build
        working-directory: product-app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: product-app/build
